version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_MANAGEMENT_IP=192.168.137.196
    volumes:
      - ~/.container-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.container-data/rabbitmq/log/:/var/lib/rabbitmq/
