# Generated by Django 4.1.3 on 2023-03-24 12:50

import crokiclothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aug_model', models.FileField(blank=True, upload_to=crokiclothes.models.upload_models_path_2)),
                ('texture', models.ImageField(blank=True, upload_to=crokiclothes.models.upload_texture_path_2)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('coverimages', models.ImageField(blank=True, upload_to=crokiclothes.models.upload_path)),
                ('convertingimages', models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path)),
                ('aug_model', models.FileField(blank=True, default='Storage/AugModels/texturedMesh.obj', upload_to=crokiclothes.models.upload_models_path)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('wearable_part', models.CharField(choices=[('TOP', 'Top'), ('BM', 'Bottom'), ('FL', 'Full')], default='TOP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesToConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convertingimages', models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path_2)),
                ('aug_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.arobject')),
            ],
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimages', models.ImageField(blank=True, upload_to=crokiclothes.models.upload_path_2)),
                ('cloth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.clothes_v2')),
            ],
        ),
        migrations.AddField(
            model_name='arobject',
            name='cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.clothes_v2'),
        ),
    ]
