# Generated by Django 4.1.3 on 2023-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='coverimages',
            field=models.ImageField(blank=True, upload_to='Storage/CoverImages'),
        ),
    ]
