# Generated by Django 4.1.3 on 2023-03-27 13:05

import crokiclothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_images', models.ImageField(blank=True, upload_to=crokiclothes.models.textures_images)),
                ('aug_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.arobject')),
            ],
        ),
    ]
