# Generated by Django 4.1.3 on 2023-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0002_alter_clothes_coverimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='aug_model',
            field=models.FileField(blank=True, default='Storage/AugModels/default-model.usdz', upload_to='Storage/AugModels'),
        ),
    ]
