# Generated by Django 4.1.3 on 2023-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0003_clothes_aug_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='aug_model',
            field=models.FileField(default='Storage/AugModels/texturedMesh.obj', upload_to='Storage/AugModels'),
        ),
    ]
