# Generated by Django 4.1.3 on 2023-03-03 15:54

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0004_alter_clothes_aug_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='aug_model',
            field=models.FileField(default='Storage/AugModels/texturedMesh.obj', upload_to=crokiclothes.models.upload_models_path),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='coverimages',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.upload_path),
        ),
    ]
