# Generated by Django 4.1.3 on 2023-03-10 08:40

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0005_alter_clothes_aug_model_alter_clothes_coverimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='convertingimages',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='aug_model',
            field=models.FileField(blank=True, default='Storage/AugModels/texturedMesh.obj', upload_to=crokiclothes.models.upload_models_path),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
