# Generated by Django 4.1.3 on 2023-03-10 09:09

import crokiclothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0006_clothes_convertingimages_alter_clothes_aug_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ar_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aug_model', models.FileField(blank=True, upload_to=crokiclothes.models.upload_models_path)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path)),
                ('aug_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crokiclothes.ar_object')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesToConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimages', models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path)),
                ('cloth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crokiclothes.clothes_v2')),
            ],
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimages', models.ImageField(blank=True, upload_to=crokiclothes.models.upload_path)),
                ('cloth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crokiclothes.clothes_v2')),
            ],
        ),
        migrations.AddField(
            model_name='ar_object',
            name='cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crokiclothes.clothes_v2'),
        ),
    ]
