# Generated by Django 4.1.3 on 2023-03-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0007_ar_object_clothes_v2_textures_imagestoconvert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestoconvert',
            name='aug_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crokiclothes.ar_object'),
        ),
    ]
