# Generated by Django 4.1.3 on 2023-03-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0008_imagestoconvert_aug_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ar_object',
            new_name='ArObject',
        ),
    ]
