# Generated by Django 4.1.3 on 2023-03-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0009_rename_ar_object_arobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestoconvert',
            name='cloth',
        ),
    ]
