# Generated by Django 4.1.3 on 2023-03-10 10:25

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0010_remove_imagestoconvert_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='aug_model',
            field=models.FileField(blank=True, upload_to=crokiclothes.models.upload_models_path_2),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='coverimages',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.upload_path_2),
        ),
        migrations.AlterField(
            model_name='imagestoconvert',
            name='coverimages',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path_2),
        ),
        migrations.AlterField(
            model_name='textures',
            name='texture',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.converting_images_path_2),
        ),
    ]
