# Generated by Django 4.1.3 on 2023-03-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0011_alter_arobject_aug_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagestoconvert',
            old_name='coverimages',
            new_name='convertingimages',
        ),
    ]
