# Generated by Django 4.1.3 on 2023-03-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0012_rename_coverimages_imagestoconvert_convertingimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.clothes_v2'),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.clothes_v2'),
        ),
        migrations.AlterField(
            model_name='imagestoconvert',
            name='aug_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.arobject'),
        ),
        migrations.AlterField(
            model_name='textures',
            name='aug_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.arobject'),
        ),
    ]
