# Generated by Django 4.1.3 on 2023-03-10 14:10

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0013_alter_arobject_cloth_alter_coverimage_cloth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='texture',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.upload_texture_path_2),
        ),
    ]
