# Generated by Django 4.1.3 on 2023-03-10 15:06

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0014_alter_textures_texture'),
    ]

    operations = [
        migrations.AddField(
            model_name='arobject',
            name='texture',
            field=models.ImageField(blank=True, upload_to=crokiclothes.models.upload_texture_path_2),
        ),
        migrations.DeleteModel(
            name='Textures',
        ),
    ]
