# Generated by Django 4.1.3 on 2023-03-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0015_arobject_texture_delete_textures'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearablePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom')], max_length=50)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crokiclothes.clothes_v2')),
            ],
        ),
    ]
