# Generated by Django 4.1.3 on 2023-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0016_wearablepart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WearablePart',
        ),
    ]
