# Generated by Django 4.1.3 on 2023-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0017_delete_wearablepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_v2',
            name='wearable_part',
            field=models.CharField(choices=[('TOP', 'Top'), ('BM', 'Bottom'), ('FL', 'Full')], default='TOP', max_length=3),
        ),
    ]
