# Generated by Django 4.1.3 on 2023-03-20 09:06

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0018_clothes_v2_wearable_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='aug_model',
            field=models.FileField(blank=True, default='AugModels/Default/Black_coat_mesh.obj', upload_to=crokiclothes.models.upload_models_path_2),
        ),
    ]
