# Generated by Django 4.1.3 on 2023-03-20 09:35

import crokiclothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crokiclothes', '0019_alter_arobject_aug_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='aug_model',
            field=models.FileField(blank=True, upload_to=crokiclothes.models.upload_models_path_2),
        ),
    ]
